const itemPoolBasePath = "assets/stitch_app/bilder_karten";

const itemPools = {
    nahrung: [
        { name: "Waldbeere", value: 1, effect: "Stellt 1 Leben wieder her", type: "Konsum", category: "Nahrung", icon: "restaurant", image: `${itemPoolBasePath}/nahrung/waldbeere.png` },
        { name: "Turmeichensamen", value: 2, effect: "Stellt 5 Mana wieder her", type: "Konsum", category: "Nahrung", icon: "restaurant", image: `${itemPoolBasePath}/nahrung/turmeichensamen.png` },
        { name: "Seraphis", value: 3, effect: "Stellt 3 Leben wieder her", type: "Konsum", category: "Nahrung", icon: "restaurant", image: `${itemPoolBasePath}/nahrung/seraphis.png` },
        { name: "Rabenkraut", value: 3, effect: "Stellt 10 Mana wieder her", type: "Konsum", category: "Nahrung", icon: "restaurant", image: `${itemPoolBasePath}/nahrung/rabenkraut.png` },
        { name: "Orkblatt", value: 5, effect: "Stellt 5 Leben wieder her", type: "Konsum", category: "Nahrung", icon: "restaurant", image: `${itemPoolBasePath}/nahrung/orkblatt.png` },
        { name: "Heilkraut", value: 2, effect: "Stellt 2 Leben wieder her", type: "Konsum", category: "Nahrung", icon: "restaurant", image: `${itemPoolBasePath}/nahrung/heilkraut.png` },
        { name: "Dunkelkraut", value: 4, effect: "Stellt 15 Mana wieder her", type: "Konsum", category: "Nahrung", icon: "restaurant", image: `${itemPoolBasePath}/nahrung/dunkelkraut.png` },
        { name: "Drachenwurzel", value: 5, effect: "Stellt 20 Mana wieder her", type: "Konsum", category: "Nahrung", icon: "restaurant", image: `${itemPoolBasePath}/nahrung/drachenwurzel.png` },
        { name: "Schinken", value: 5, effect: "Stellt 5 Leben wieder her", type: "Konsum", category: "Nahrung", icon: "restaurant", image: `${itemPoolBasePath}/nahrung/schinken.png` }
    ],
    waffen: [
        // Nahkampf - Kapitel 1
        { name: "Altes Schwert", value: 20, chapter: 1, class: 2, style: "Nahkampf", art: "Einhandwaffe", req: "1 STR", damage: 3, type: "Klingenwaffe", ability: "keine", category: "Waffen", icon: "swords", image: `${itemPoolBasePath}/waffen/kapitel_1/altes_schwert.png` },
        { name: "Buddlerzucht", value: 40, chapter: 1, class: 3, style: "Nahkampf", art: "Einhandwaffe", req: "2 STR", damage: 4, type: "Klingenwaffe", ability: "Keine", category: "Waffen", icon: "swords", image: `${itemPoolBasePath}/waffen/kapitel_1/buddlerzucht.png` },
        { name: "Keule", value: 10, chapter: 1, class: 1, style: "Nahkampf", art: "Einhandwaffe", req: "1 STR", damage: 1, type: "Stumpfe Waffe", ability: "Keine", category: "Waffen", icon: "swords", image: `${itemPoolBasePath}/waffen/kapitel_1/keule.png` },
        { name: "Knüppel", value: 2, chapter: 1, class: 1, style: "Nahkampf", art: "Einhandwaffe", req: "1 STR", damage: 1, type: "Stumpfe Waffe", ability: "Keine", category: "Waffen", icon: "swords", image: `${itemPoolBasePath}/waffen/kapitel_1/knueppel.png` },
        { name: "Rostiges Schwert", value: 10, chapter: 1, class: 1, style: "Nahkampf", art: "Einhandwaffe", req: "1 STR", damage: 2, type: "Klingenwaffe", ability: "Keine", category: "Waffen", icon: "swords", image: `${itemPoolBasePath}/waffen/kapitel_1/rostiges_schwert.png` },
        { name: "Schmiedehammer", value: 10, chapter: 1, class: 1, style: "Nahkampf", art: "Einhandwaffe", req: "1 STR", damage: 2, type: "Stumpfe Waffe", ability: "Keine", category: "Waffen", icon: "swords", image: `${itemPoolBasePath}/waffen/kapitel_1/schmiedehammer.png` },
        { name: "Spitzhacke", value: 10, chapter: 1, class: 1, style: "Nahkampf", art: "Zweihandwaffe", req: "1 STR", damage: 2, type: "Stumpfe Waffe", ability: "ignoriert 1 Rüstung vom Gegner im Kampf", category: "Waffen", icon: "architecture", image: `${itemPoolBasePath}/waffen/kapitel_1/spitzhacke.png` },
        { name: "Verwitterte Axt", value: 20, chapter: 1, class: 2, style: "Nahkampf", art: "Einhandwaffe", req: "1 STR", damage: 3, type: "Klingenwaffe", ability: "Keine", category: "Waffen", icon: "swords", image: `${itemPoolBasePath}/waffen/kapitel_1/verwitterte_axt.png` },
        
        // Nahkampf - Kapitel 2
        { name: "Gardesschwert", value: 30, chapter: 2, class: 1, style: "Nahkampf", art: "Einhandwaffe", req: "2 STR", damage: 4, type: "Klingenwaffe", ability: "Schlächter 1", category: "Waffen", icon: "swords", image: `${itemPoolBasePath}/waffen/kapitel_2/gardesschwert.png` },
        { name: "Herrscherstab", value: 40, chapter: 2, class: 2, style: "Nahkampf", art: "Zweihandwaffe", req: "4 STR", damage: 6, type: "Klingenwaffe", ability: "Schnelle Hiebe", category: "Waffen", icon: "swords", image: `${itemPoolBasePath}/waffen/kapitel_2/herrscherstab.png` },
        { name: "Kampfschwert", value: 40, chapter: 2, class: 2, style: "Nahkampf", art: "Einhandwaffe", req: "3 STR", damage: 5, type: "Klingenwaffe", ability: "Parade 5", category: "Waffen", icon: "swords", image: `${itemPoolBasePath}/waffen/kapitel_2/kampfschwert.png` },
        { name: "Kampfstab", value: 20, chapter: 2, class: 1, style: "Nahkampf", art: "Zweihandwaffe", req: "1 STR", damage: 3, type: "Stumpfe Waffe", ability: "Aura +5 Mana", category: "Waffen", icon: "swords", image: `${itemPoolBasePath}/waffen/kapitel_2/kampfstab.png` },
        { name: "Krush Var`ok", value: 50, chapter: 2, class: 3, style: "Nahkampf", art: "Zweihandwaffe", req: "6 STR", damage: 8, type: "Klingenwaffe", ability: "Brutalismus 6/4", category: "Waffen", icon: "swords", image: `${itemPoolBasePath}/waffen/kapitel_2/krush_varrok.png` },
        { name: "Rostige Streitaxt", value: 20, chapter: 2, class: 1, style: "Nahkampf", art: "Zweihandwaffe", req: "5 STR", damage: 5, type: "Klingenwaffe", ability: "Wuchtschlag 6/3", category: "Waffen", icon: "swords", image: `${itemPoolBasePath}/waffen/kapitel_2/rostige_streitaxt.png` },
        { name: "Stachelkeule", value: 40, chapter: 2, class: 2, style: "Nahkampf", art: "Einhandwaffe", req: "3 STR", damage: 5, type: "Stumpfe Waffe", ability: "Knüppel auf den Sack 4", category: "Waffen", icon: "swords", image: `${itemPoolBasePath}/waffen/kapitel_2/stachelkeule.png` },
        { name: "Steinbrecher", value: 50, chapter: 2, class: 3, style: "Nahkampf", art: "Einhandwaffe", req: "4 STR", damage: 6, type: "Stumpfe Waffe", ability: "Chitinknacker und Golemhammer 4", category: "Waffen", icon: "swords", image: `${itemPoolBasePath}/waffen/kapitel_2/steinbrecher.png` },
        { name: "Streitkolben", value: 30, chapter: 2, class: 1, style: "Nahkampf", art: "Einhandwaffe", req: "1 STR", damage: 3, type: "Stumpfe Waffe", ability: "Chitinknacker 3", category: "Waffen", icon: "swords", image: `${itemPoolBasePath}/waffen/kapitel_2/streitkolben.png` },

        // Fernkampf
        { name: "Kurzbogen", value: 10, chapter: 1, class: 1, style: "Fernkampf", art: "Bogen", req: "2 DEX", damage: 1, ability: "Keine", category: "Waffen", icon: "precision_manufacturing", image: `${itemPoolBasePath}/waffen/kapitel_1/kurzbogen.png` },
        { name: "Reiterbogen", value: 20, chapter: 1, class: 2, style: "Fernkampf", art: "Bogen", req: "3 DEX", damage: 2, ability: "Flinkheit 1", category: "Waffen", icon: "precision_manufacturing", image: `${itemPoolBasePath}/waffen/kapitel_1/reiterbogen.png` },
        { name: "Feldbogen", value: 30, chapter: 2, class: 1, style: "Fernkampf", art: "Bogen", req: "2 DEX", damage: 2, ability: "Querfeldein 1", category: "Waffen", icon: "precision_manufacturing", image: `${itemPoolBasePath}/waffen/kapitel_2/feldbogen.png` },
        { name: "Jagdbogen", value: 40, chapter: 2, class: 2, style: "Fernkampf", art: "Bogen", req: "4 DEX", damage: 3, ability: "Jäger 2", category: "Waffen", icon: "precision_manufacturing", image: `${itemPoolBasePath}/waffen/kapitel_2/jagdbogen.png` },
        { name: "Knochenbogen", value: 50, chapter: 2, class: 3, style: "Fernkampf", art: "Bogen", req: "5 DEX", damage: 4, ability: "Marktreffer 5", category: "Waffen", icon: "precision_manufacturing", image: `${itemPoolBasePath}/waffen/kapitel_2/knochenbogen.png` },
        { name: "Leichte Armbrust", value: 40, chapter: 2, class: 2, style: "Fernkampf", art: "Armbrust", req: "5 DEX", damage: 5, ability: "Vorgeladen", category: "Waffen", icon: "precision_manufacturing", image: `${itemPoolBasePath}/waffen/kapitel_2/leichte_armbrust.png` }
    ],
    ausruestung: [
        { name: "Amulett der Überdauerung", value: 40, chapter: "1 & 2", art: "Artefakt", effect: "Aura +3 Lebenspunkte", category: "Ausrüstung", icon: "trip_origin", image: `${itemPoolBasePath}/ausruestung/kapitel_1_und_2/amulett_der_ueberdauerung.png` },
        { name: "Bierchen", value: 5, chapter: "1 & 2", art: "Konsum", effect: "+1 Stärke und – 1 Geschick und Bewegung im nächsten Kampf", category: "Ausrüstung", icon: "restaurant", image: `${itemPoolBasePath}/ausruestung/kapitel_1_und_2/bierchen.png` },
        { name: "Der gute Dietrich", value: 20, chapter: "1 & 2", art: "Artefakt", effect: "bei jeder Truhe sinkt der TSW um 2, wird bei nicht Erfolg einer Truhe aus dem Inventar entfernt", category: "Ausrüstung", icon: "handyman", image: `${itemPoolBasePath}/ausruestung/kapitel_1_und_2/der_gute_dietrich.png` },
        { name: "Eisenamulett", value: 40, chapter: "1 & 2", art: "Artefakt", effect: "Aura +1 Rüstung", category: "Ausrüstung", icon: "trip_origin", image: `${itemPoolBasePath}/ausruestung/kapitel_1_und_2/eisenamulett.png` },
        { name: "Grüner Novize", value: 20, chapter: "1 & 2", art: "Konsum", effect: "+30*Kapitel Erfahrung", category: "Ausrüstung", icon: "filter_vintage", image: `${itemPoolBasePath}/ausruestung/kapitel_1_und_2/gruener_novize.png` },
        { name: "Heiltrank klein", value: 15, chapter: "1 & 2", art: "Konsum", effect: "Stellt 15 Leben wieder her", category: "Ausrüstung", icon: "ecg_heart", image: `${itemPoolBasePath}/ausruestung/kapitel_1_und_2/heiltrank_klein.png` },
        { name: "kleine Essenz der Magie", value: 15, chapter: "1 & 2", art: "Konsum", effect: "Stellt 30 Mana wieder her", category: "Ausrüstung", icon: "magic_button", image: `${itemPoolBasePath}/ausruestung/kapitel_1_und_2/kleine_essenz_der_magie.png` },
        { name: "Köder", value: 10, chapter: "1 & 2", art: "Konsum", effect: "ermöglicht Flucht vor einem Raubtier oder kann als Alternative zur Angreifen Karte genutzt werden, um eins anzulocken", category: "Ausrüstung", icon: "set_meal", image: `${itemPoolBasePath}/ausruestung/kapitel_1_und_2/koeder.png` },
        { name: "Ring der Bewegungsfreude", value: 30, chapter: "1 & 2", art: "Artefakt", effect: "Aura +1 Geschick", category: "Ausrüstung", icon: "trip_origin", image: `${itemPoolBasePath}/ausruestung/kapitel_1_und_2/ring_der_bewegungsfreude.png` },
        { name: "Ring der Geistesratsamkeit", value: 30, chapter: "1 & 2", art: "Artefakt", effect: "Aura +5 Mana", category: "Ausrüstung", icon: "trip_origin", image: `${itemPoolBasePath}/ausruestung/kapitel_1_und_2/ring_der_geistesratsamkeit.png` },
        { name: "Ring der Raufbolde", value: 30, chapter: "1 & 2", art: "Artefakt", effect: "Aura +1 Stärke", category: "Ausrüstung", icon: "trip_origin", image: `${itemPoolBasePath}/ausruestung/kapitel_1_und_2/ring_der_raufbolde.png` },
        { name: "Schwarzer Weiser", value: 20, chapter: "1 & 2", art: "Konsum", effect: "+1 Maximales Mana", category: "Ausrüstung", icon: "filter_vintage", image: `${itemPoolBasePath}/ausruestung/kapitel_1_und_2/schwarzer_weiser.png` },
        { name: "starke Bogensehne", value: 30, chapter: "1 & 2", art: "Konsum", effect: "+1 Schaden auf ausgewählten Bogen", category: "Ausrüstung", icon: "handyman", image: `${itemPoolBasePath}/ausruestung/kapitel_1_und_2/starke_bogensehne.png` },
        { name: "Trank der Geschwindigkeit", value: 20, chapter: "1 & 2", art: "Konsum", effect: "Verdoublet im nächsten Zug die Anzahl an Feldern der Bewegungskarten", category: "Ausrüstung", icon: "speed", image: `${itemPoolBasePath}/ausruestung/kapitel_1_und_2/trank_der_geschwindigkeit.png` },
        { name: "Wetzstein", value: 15, chapter: "1 & 2", art: "Konsum", effect: "+1 Schaden auf ausgewählte Klingenwaffe", category: "Ausrüstung", icon: "handyman", image: `${itemPoolBasePath}/ausruestung/kapitel_1_und_2/wetzstein.png` },
        { name: "Zielfernrohr", value: 20, chapter: "1 & 2", art: "Konsum", effect: "+1 Schaden auf ausgewählte Armbrust", category: "Ausrüstung", icon: "center_focus_strong", image: `${itemPoolBasePath}/ausruestung/kapitel_1_und_2/zielfernrohr.png` }
    ],
    ruestung: [
        { name: "Sträflingsklamotten", value: 0, chapter: 0, effect: "Aura +3 Rüstung", category: "Rüstung", icon: "shield", image: `${itemPoolBasePath}/ruestungen/kapitel_1_und_2/straeflingsklamotten.png` },
        { name: "Schürferhose", value: 100, chapter: "1 & 2", effect: "Aura +4 Rüstung", category: "Rüstung", icon: "shield", image: `${itemPoolBasePath}/ruestungen/kapitel_1_und_2/schuerferhose.png` },
        { name: "Novizenrock", value: 110, chapter: "1 & 2", effect: "Aura +4 Rüstung und +1 Schutz vor Magie", category: "Rüstung", icon: "shield", image: `${itemPoolBasePath}/ruestungen/kapitel_1_und_2/novizenrock.png` },
        { name: "Buddlerhose", value: 200, chapter: "1 & 2", effect: "Aura +5 Rüstung", category: "Rüstung", icon: "shield", image: `${itemPoolBasePath}/ruestungen/kapitel_1_und_2/buddlerhose.png` }
    ],
    magie: [
        // Spruchrollen - Kapitel 1 & 2
        { name: "Eisblock Spruchrolle", value: 15, chapter: "1 & 2", art: "Spruchrolle", maxCapacity: 3, style: "Aufladbar", element: "Eis", reqMana: 1, maxMana: 4, damage: 2, effect: "Lähmung 2", trigger: "maximal", category: "Magie", icon: "ac_unit", image: `${itemPoolBasePath}/magie/kapitel_1/eisblock_spruchrolle.png` },
        { name: "Feuerball Spruchrolle", value: 10, chapter: "1 & 2", art: "Spruchrolle", maxCapacity: 3, style: "Aufladbar", element: "Feuer", reqMana: 1, maxMana: 5, damage: 3, effect: "reduziert Rüstung des Gegners für 2 Runden auf 0", trigger: "maximal", category: "Magie", icon: "local_fire_department", image: `${itemPoolBasePath}/magie/kapitel_1/feuerball_spruchrolle.png` },
        { name: "Heilung Spruchrolle", value: 5, chapter: "1 & 2", art: "Spruchrolle", maxCapacity: 5, style: "Aufladbar", element: "Heilig", reqMana: 1, maxMana: 100, damage: 0, effect: "stellt pro Mana 3 Leben an dir oder angrenzenden Verbündeten wieder her", trigger: "immer", category: "Magie", icon: "ecg_heart", image: `${itemPoolBasePath}/magie/kapitel_1/heilung_spruchrolle.png` },
        { name: "Kugelblitz Spruchrolle", value: 25, chapter: "1 & 2", art: "Spruchrolle", maxCapacity: 3, style: "Aufladbar", element: "Blitz", reqMana: 3, maxMana: 15, damage: 4, effect: "Schockstarre", trigger: "maximal", category: "Magie", icon: "bolt", image: `${itemPoolBasePath}/magie/kapitel_1/kugelblitz_spruchrolle.png` },
        { name: "Windfaust Spruchrolle", value: 10, chapter: "1 & 2", art: "Spruchrolle", maxCapacity: 3, style: "Aufladbar", element: "Wind", reqMana: 1, maxMana: 3, damage: 3, effect: "Schleudern 2", trigger: "immer", category: "Magie", icon: "air", image: `${itemPoolBasePath}/magie/kapitel_1/windfaust_spruchrolle.png` },
        { name: "Sturmfaust Spruchrolle", value: 30, chapter: "1 & 2", art: "Spruchrolle", maxCapacity: 3, style: "Aufladbar", element: "Wind", reqMana: 3, maxMana: 12, damage: 5, effect: "Wuchtschleudern", trigger: "maximal", category: "Magie", icon: "cyclone", image: `${itemPoolBasePath}/magie/kapitel_1/sturmfaust_spruchrolle.png` },
        { name: "Eispfeil Spruchrolle", value: 5, chapter: "1 & 2", art: "Spruchrolle", maxCapacity: 5, style: "Sofort", element: "Eis", reqMana: 2, damage: 4, effect: "Verlangsamung 1 / 1", category: "Magie", icon: "ac_unit", image: `${itemPoolBasePath}/magie/kapitel_1/eispfeil_spruchrolle.png` },
        { name: "Feuerpfeil Spruchrolle", value: 5, chapter: "1 & 2", art: "Spruchrolle", maxCapacity: 5, style: "Sofort", element: "Feuer", reqMana: 2, damage: 5, effect: "Keine", category: "Magie", icon: "local_fire_department", image: `${itemPoolBasePath}/magie/kapitel_1/feuerpfeil_spruchrolle.png` },
        { name: "Schlaf Spruchrolle", value: 10, chapter: "1 & 2", art: "Spruchrolle", maxCapacity: 3, style: "Sofort", element: "Schläfer", reqMana: 5, damage: 0, effect: "Schlaf 3", category: "Magie", icon: "bedtime", image: `${itemPoolBasePath}/magie/kapitel_1/schlaf_spruchrolle.png` },

        // Runen - Kapitel 2 & 3
        { name: "Eisblock Rune", value: 250, chapter: "2 & 3", art: "Rune", circle: 2, style: "Aufladbar", element: "Eis", reqMana: 1, maxMana: 4, damage: 2, effect: "Lähmung 2", trigger: "maximal", category: "Magie", icon: "ac_unit", image: `${itemPoolBasePath}/magie/kapitel_2/eisblock_rune.png` },
        { name: "Feuerball Rune", value: 200, chapter: "2 & 3", art: "Rune", circle: 2, style: "Aufladbar", element: "Feuer", reqMana: 1, maxMana: 5, damage: 3, effect: "Keiner", category: "Magie", icon: "local_fire_department", image: `${itemPoolBasePath}/magie/kapitel_2/feuerball_rune.png` },
        { name: "Heilung Rune", value: 100, chapter: "2 & 3", art: "Rune", circle: 1, style: "Aufladbar", element: "Heilig", reqMana: 1, maxMana: 5, damage: 0, effect: "stellt pro Mana 3 Leben an dir oder angrenzenden Verbündeten wieder her", trigger: "immer", category: "Magie", icon: "ecg_heart", image: `${itemPoolBasePath}/magie/kapitel_2/heilung_rune.png` },
        { name: "Kugelblitz Rune", value: 250, chapter: "2 & 3", art: "Rune", circle: 2, style: "Aufladbar", element: "Blitz", reqMana: 3, maxMana: 15, damage: 4, effect: "Schockstarre", trigger: "maximal", category: "Magie", icon: "bolt", image: `${itemPoolBasePath}/magie/kapitel_2/kugelblitz_rune.png` },
        { name: "Windfaust Rune", value: 150, chapter: "2 & 3", art: "Rune", circle: 1, style: "Aufladbar", element: "Wind", reqMana: 1, maxMana: 3, damage: 3, effect: "Schleudern 3", trigger: "immer", category: "Magie", icon: "air", image: `${itemPoolBasePath}/magie/kapitel_2/windfaust_rune.png` },
        { name: "Sturmfaust Rune", value: 250, chapter: "2 & 3", art: "Rune", circle: 2, style: "Aufladbar", element: "Wind", reqMana: 3, maxMana: 12, damage: 5, effect: "Wuchtschleudern", trigger: "maximal", category: "Magie", icon: "cyclone", image: `${itemPoolBasePath}/magie/kapitel_2/sturmfaust_rune.png` },
        { name: "Eispfeil Rune", value: 150, chapter: "2 & 3", art: "Rune", circle: 1, style: "Sofort", element: "Eis", reqMana: 2, damage: 4, effect: "Verlangsamung 1 / 1", category: "Magie", icon: "ac_unit", image: `${itemPoolBasePath}/magie/kapitel_2/eispfeil_rune.png` },
        { name: "Feuerpfeil Rune", value: 100, chapter: "2 & 3", art: "Rune", circle: 1, style: "Sofort", element: "Feuer", reqMana: 2, damage: 5, effect: "Keine", category: "Magie", icon: "local_fire_department", image: `${itemPoolBasePath}/magie/kapitel_2/feuerpfeil_rune.png` },
        { name: "Schlaf Rune", value: 150, chapter: "2 & 3", art: "Rune", circle: 1, style: "Sofort", element: "Schläfer", reqMana: 5, damage: 0, effect: "Schlaf 3", category: "Magie", icon: "bedtime", image: `${itemPoolBasePath}/magie/kapitel_2/schlaf_rune.png` }
    ]
};
